import json

with open("notebooks/test.ipynb", "r") as f:
    nb = json.load(f)

new_source = [
    "import pandas as pd\n",
    "import plotly.graph_objects as go\n",
    "import numpy as np\n",
    "\n",
    "# 1. Load data\n",
    "df = pd.read_csv(\"../data/processed/eurostat_insights.csv\")\n",
    "# Filter timeline from 2014 to 2024\n",
    "df = df[(df[\"Year\"] >= 2014) & (df[\"Year\"] <= 2024)]\n",
    "\n",
    "EU_ISO2_TO_ISO3 = {\"AT\":\"AUT\",\"BE\":\"BEL\",\"BG\":\"BGR\",\"CY\":\"CYP\",\"CZ\":\"CZE\",\"DE\":\"DEU\",\"DK\":\"DNK\",\"EE\":\"EST\",\"ES\":\"ESP\",\"FI\":\"FIN\",\"FR\":\"FRA\",\"GR\":\"GRC\",\"EL\":\"GRC\",\"HR\":\"HRV\",\"HU\":\"HUN\",\"IE\":\"IRL\",\"IT\":\"ITA\",\"LT\":\"LTU\",\"LU\":\"LUX\",\"LV\":\"LVA\",\"MT\":\"MLT\",\"NL\":\"NLD\",\"PL\":\"POL\",\"PT\":\"PRT\",\"RO\":\"ROU\",\"SE\":\"SWE\",\"SI\":\"SVN\",\"SK\":\"SVK\",\"UK\":\"GBR\"}\n",
    "COUNTRY_COORDS = {\"AUT\":(47.8,13.3),\"BEL\":(50.8,4.4),\"BGR\":(42.7,25.5),\"CYP\":(35.1,33.4),\"CZE\":(49.8,15.5),\"DEU\":(51.2,10.4),\"DNK\":(56.3,9.5),\"EST\":(58.6,25.0),\"ESP\":(40.4,-3.7),\"FIN\":(61.9,25.7),\"FRA\":(46.2,2.2),\"GRC\":(39.1,21.8),\"HRV\":(45.1,15.2),\"HUN\":(47.2,19.5),\"IRL\":(53.4,-8.2),\"ITA\":(41.9,12.6),\"LTU\":(55.2,23.9),\"LUX\":(49.8,6.1),\"LVA\":(57.0,24.8),\"MLT\":(35.9,14.5),\"NLD\":(52.1,5.3),\"POL\":(51.9,19.1),\"PRT\":(39.4,-8.2),\"ROU\":(45.9,24.9),\"SWE\":(60.1,18.6),\"SVN\":(46.1,14.8),\"SVK\":(48.7,19.7),\"GBR\":(55.4,-3.4)}\n",
    "\n",
    "df[\"ISO3\"] = df[\"Country\"].map(EU_ISO2_TO_ISO3)\n",
    "pivoted = df.pivot_table(index=[\"Year\",\"ISO3\",\"Country\"], columns=\"Metric\", values=\"Gap_ExtraEU_vs_Native_PP\").reset_index()\n",
    "\n",
    "# Ensure consistent rows across all years for animation stability\n",
    "all_years = sorted(df[\"Year\"].unique())\n",
    "all_iso3 = list(COUNTRY_COORDS.keys())\n",
    "idx = pd.MultiIndex.from_product([all_years, all_iso3], names=[\"Year\", \"ISO3\"])\n",
    "pivoted = pivoted.set_index([\"Year\", \"ISO3\"]).reindex(idx).reset_index()\n",
    "\n",
    "# Restore missing Country names\n",
    "iso3_to_country = df.drop_duplicates(\"ISO3\").set_index(\"ISO3\")[\"Country\"].to_dict()\n",
    "pivoted[\"Country\"] = pivoted[\"ISO3\"].map(iso3_to_country)\n",
    "\n",
    "pivoted[\"lat\"] = pivoted[\"ISO3\"].map(lambda x: COUNTRY_COORDS.get(x,(None,None))[0])\n",
    "pivoted[\"lon\"] = pivoted[\"ISO3\"].map(lambda x: COUNTRY_COORDS.get(x,(None,None))[1])\n",
    "pivoted = pivoted.dropna(subset=[\"lat\",\"lon\"])\n",
    "\n",
    "years = sorted(pivoted[\"Year\"].unique())\n",
    "max_temp = pivoted[\"Temporary_Contract_Rate\"].abs().max()\n",
    "min_pov = pivoted[\"Poverty_Rate\"].min()\n",
    "max_pov = pivoted[\"Poverty_Rate\"].max()\n",
    "\n",
    "def make_trace(sub):\n",
    "    # Base sizes based on Temporary_Contract_Rate.\n",
    "    raw_sizes = sub[\"Temporary_Contract_Rate\"].abs() / max_temp * 40 + 7\n",
    "    \n",
    "    # If data is completely missing for a country, set its size to 0 to make it invisible \n",
    "    # (avoiding the transparent outline issue) while keeping it in the dataframe to maintain animation order.\n",
    "    # We check if ALL relevant metrics are NaN\n",
    "    missing_all = sub[[\"Temporary_Contract_Rate\", \"Poverty_Rate\", \"Highly_Educated_Employment_Rate\"]].isna().all(axis=1)\n",
    "    sizes = np.where(missing_all, 0, raw_sizes.fillna(7))\n",
    "    \n",
    "    display_color = sub[\"Poverty_Rate\"].fillna(-99)\n",
    "    custom_reds = [\n",
    "        [0, 'rgb(120,120,120)'], \n",
    "        [0.01, 'rgb(120,120,120)'],\n",
    "        [0.02, 'rgb(255,245,240)'], \n",
    "        [1, 'rgb(103,0,13)']       \n",
    "    ]\n",
    "\n",
    "    return go.Scattergeo(\n",
    "        lat=sub[\"lat\"], lon=sub[\"lon\"],\n",
    "        mode=\"markers\",\n",
    "        marker=dict(\n",
    "            size=sizes,\n",
    "            color=display_color,\n",
    "            colorscale=custom_reds,\n",
    "            cmin=-100, \n",
    "            cmax=max_pov,\n",
    "            showscale=True,\n",
    "            colorbar=dict(\n",
    "                title=\"Poverty Gap\",\n",
    "                tickvals=[min_pov, (min_pov+max_pov)/2, max_pov],\n",
    "                ticktext=[f\"{min_pov:.0f}\", \"Medium\", f\"{max_pov:.0f} (High)\"]\n",
    "            ),\n",
    "            opacity=0.9,\n",
    "            # Only draw a line if the size > 0 so invisible points stay invisible\n",
    "            line=dict(width=1, color=\"rgba(255,255,255,0.5)\")\n",
    "        ),\n",
    "        customdata=sub[[\"Country\", \"Highly_Educated_Employment_Rate\", \"Poverty_Rate\", \"Temporary_Contract_Rate\"]],\n",
    "        hovertemplate=(\n",
    "            \"<b>%{customdata[0]}</b><br>\"\n",
    "            \"Emp. Gap: %{customdata[1]:.1f}pp<br>\"\n",
    "            \"Poverty Gap: %{customdata[2]:.1f}pp<br>\"\n",
    "            \"Temp Contract Gap: %{customdata[3]:.1f}pp<extra></extra>\"\n",
    "        )\n",
    "    )\n",
    "\n",
    "fig = go.Figure(\n",
    "    data=[make_trace(pivoted[pivoted[\"Year\"] == years[0]])],\n",
    "    frames=[go.Frame(data=[make_trace(pivoted[pivoted[\"Year\"] == y])], name=str(y)) for y in years],\n",
    "    layout=go.Layout(\n",
    "        title=dict(text=\"<b>European Brain Waste Paradox</b> (2014-2024)<br><sup>Gray = Poverty Data Missing for that year</sup>\", x=0.5),\n",
    "        geo=dict(scope=\"europe\", projection_type=\"natural earth\", showland=True, landcolor=\"#1c1e26\", bgcolor=\"#0d1117\"),\n",
    "        paper_bgcolor=\"#0d1117\", font=dict(color=\"white\"),\n",
    "        height=700,\n",
    "        updatemenus=[dict(type=\"buttons\", x=0.1, y=0, buttons=[\n",
    "            dict(label=\"Play\", method=\"animate\", args=[None, {\"frame\":{\"duration\":700}}]),\n",
    "            dict(label=\"Pause\", method=\"animate\", args=[[None], {\"mode\":\"immediate\"}])\n",
    "        ])],\n",
    "        sliders=[dict(active=0, x=0.1, len=0.9, pad={\"t\": 50},\n",
    "                     currentvalue=dict(prefix=\"Year: \", font=dict(size=14, color=\"white\")),\n",
    "                     steps=[dict(args=[[str(y)], {\"frame\": {\"duration\": 300, \"redraw\": True}, \"mode\": \"immediate\"}],\n",
    "                                 label=str(y), method=\"animate\") for y in years])]\n",
    "    )\n",
    ")\n",
    "\n",
    "fig.show()\n"
]

for i, cell in enumerate(nb["cells"]):
    if "bubble_map_v2" in cell["metadata"].get("tags", []) or "def make_trace" in "".join(cell["source"]):
        nb["cells"][i]["source"] = new_source
        break

with open("notebooks/test.ipynb", "w") as f:
    json.dump(nb, f, indent=1)

